### ISSUE TITLE
docs: add user case doc

### ISSUE THREAD

**Issue by chai2010** [KusionStack/kusionstack.io#64]
### 1. 三级对象： 应用、环境、集群， 在大库中怎么映射合理？
**概念**
Project 是一个抽象概念，有明确的业务语意，可以映射一个应用，也可以映射成一种运维场景；
Stack 是一组可以独立部署、单独配置的 KCL 程序，是可以部署为一组基础设施实体的最小配置单元；
**映射关系**
云原生场景：应用和集群

- Project -> 应用
- Stack -> 集群

单租户场景：应用和环境

- Project  -> 应用
- Stack -> 环境

多租户场景：应用和环境

- Project -> 多租户间唯一的应用名称
- Stack -> 环境

**实践**
按照上面映射关系的推荐，问题中提到的三级对象，可以互相嵌套：
应用是关注的核心对象，环境与集群是应用的描述属性，是多对多关系，也就是存在多种环境（dev/test/prod...），每个环境中有多个集群（clusterA/clusterB），可以在大库的 Project 的目录结构中增加一级，如下所示：
```
app
├── dev
│   ├── clusterA
│   │   ├── ci-test
│   │   │   ├── settings.yaml
│   │   │   └── stdout.golden.yaml
│   │   ├── kcl.yaml
│   │   ├── main.k
│   │   └── stack.yaml
│   └── clusterB
│       ├── ci-test
│       │   ├── settings.yaml
│       │   └── stdout.golden.yaml
│       ├── kcl.yaml
│       ├── main.k
│       └── stack.yaml
├── prod
├── test
└── project.yaml
```
### 2. 不同应用的不同集群间会有依赖关系(应用级别)， 在大库中怎么表达？
假设应用A依赖应用B.field_b

- 如果A，B两个应用在同一个Stack中。同一Stack中的所有资源可以通过dependsOn或$kusion_path关键字完成显示和隐式依赖
```yaml
// App A
attributes:
  field: $kusion_path.app_b.field_b
id: app_a
dependsOn:
  - app_b
  
// App B
attributes:
  field_b: xxxxx
id: app_b
```

- 如果A，B两个应用在不同Stack中。可以把B中的field_b作为一个独立资源，与应用A放在一个Stack中，应用A依赖此资源，apply此资源时，背后的Operator或者Provider去读取field_b的具体数据，再apply应用A时就可以自动完成变量替换
```yaml
// App A
attributes:
  field: $kusion_path.app_b_config.field_b
id: app_a
dependsOn:
  - app_b_config
  
// App B Config
attributes:
  field_b: xxxxx
id: app_b_config
```
### 3. github上的konfig与内部的konfig结合的推荐方式？
KusionStack 在开源之前采用了 MonoRepo 的单一大库模式（全部的配置在一个仓库）。大库模式的优点配置依赖不会出现版本冲突问题，可以在一次变更提交中批量修改配置变更。大库模式也是Google等公司内部实践，比较适合企业内部配置方便统一管理的场景。
但是，单一大库模式不太适合开源社区的去中心化的配置管理。作为一个开源工具，用户自然希望能过基于Konfig中心的模型配置仓库再扩展出自己的定制配置仓库。目前，一个临时的方案是基于Konfig克隆版本，然后新建一个独立子 `org/app` 目录作为组织下app的配置管理。
KusionStack 同时也在设计包管理工具，希望KCL语言能够提供内置包工具兼容集中式和分布式的配置模块管理。同时也欢迎提供不同的反馈或设计方案。
### 1. 有办法只对大库中修改的模块/应用做CI吗？
有，最基本的方式就是通过 `git diff` 定位修改文件列表。但修改的文件可能是公共配置，被一个或多个应用的所依赖，kusion 提供 `kusion deps` 子命令，用于分析依赖关系。
### 1. kusion apply执行完， 部署状态能否有办法通过kusion命令查看么？
kusion watch 子命令提供相关能力，此功能目前还在开发中，预计下个版本发布。
### 2. 回滚操作依赖于gitlab/github的回滚吗， 有其他可以快速回滚的方式吗？
目前回滚操作，主要是借助 git revert + kusion apply 的方式。关于 kusion 本身的 Transaction 能力，这块也在我们的规划范围内。
### 1. 身份认证和鉴权如何处理的？
kusion 会提供相关接口，可以与开源 Identity 平台对接；对于内部私有的可信平台，也会提供扩展机制，用来集成。总体来说，kusion 不负责权限的具体范围，只确定操作的 Allow or  Deny。
### 2. kusion apply是每个人都有权限操作吗？
如上个回答所示，kusion 没有对接 Identity 平台之前，是人人可操作的；对接 Identity 平台后，由 Identity 平台负责权限划分。
